#!/usr/bin/env php
<?php

// NEED TO ADD AUTOLOADER, when i transition to library/project it will get fixed
require_once 'public/autoload.php';
require_once 'helpers/helpers.php';

use bootstrap\App;
use Leonlav77\Frejmcore\console\Command;

$app = new App();

$command = new Command($argv);
$command->run();