#!/usr/bin/env php
<?php

// NEED TO ADD AUTOLOADER, when i transition to library/project it will get fixed
use console\Command;

require_once 'console\Command.php';

$command = new Command($argv);
$command->run();