#!/usr/bin/env php
<?php

require "vendor/autoload.php";

use Leonlav77\Frejmcore\console\Command;

$app = require_once __DIR__ . '/bootstrap/app.php';

$command = new Command($argv);
$command->run();